### ISSUE TITLE
Running this in browser using file://

### ISSUE THREAD

**Issue by Pokeplays09125** [copy/v86#1029]
I'm super sorry if I sound like a noob here. I've been struggling for 2 weeks to get the embedded version of v86 to run locally through my browser, and each time I have failed. They all seem to be related to the .wasm file. Is this even possible to run through my browser using file://?

**Comment by copy** [comment]
As far as I know, wasm files have to be loaded using fetch or xhr, which is blocked by browsers for security reasons. 

There's a couple of options:
- set `privacy.file_unique_origin` to `false` in about:config (firefox) or the `--allow-file-access-from-files` flag for chromium
- embed the wasm into the html file
- electron can probably load files directly (for example https://github.com/felixrieseberg/windows95)
- run a webserver

Since none of these are on v86's side, let's close this issue.

**Comment by jjr90** [comment]
> As far as I know, wasm files have to be loaded using fetch or xhr

Emscripten embeds wasm in HTML with `-sSINGLE_FILE`. The `WebAssembly.instantiate(bytes, env)` doesn't care if the bytes come from an embedded base64 or an `<input type="file">`. The **Audio worklet** was more of a concern but fixed up okay.

Here's my demo of v86 in a single HTML file that works 100% offline with no web server, using the latter approach:
https://gist.github.com/jjr90/9400b0e261de2c9ec108beba21c7225e

Disconnect internet and open it in a Private Browsing window (no cache), and load a local ISO to test.

Notes:
* Audio worklet loading: passing a Blob from a local origin to `addModule()` is not allowed. I passed it as a data URI instead, which works - but that might not be allowed in _older_ Chromium versions, according to... various AIs... (I can't find any confirmation of that).
* Since xterm.js is embedded, its onload() wouldn't trigger, so I put that code after the appendChild(). I'm sure there's a clean module-style way to embed xterm without base64.
* Sorry I didn't fork to show changes (they're trivial anyway), I will try to later for OP.
---
Offline single-file HTML builds are useful for getting around code-signing/notarization lockdowns on OSes, including Android soon.

By 2027, even Developer-Verified APKs won't install on Android without an internet connection for Google services to verify them.

In offline (e.g. post-war) conditions, this neuters Android as a portable general computer, unless you pack a computer into an HTML file with no relative paths.

---

Despite that it seems to work fine, I can't isolate this console error, which shows only in Chromium and only when opening the file directly from my desktop (macOS):

> Unsafe attempt to load URL file:///Users/me/v86_offline_file.html from frame with URL file:///Users/me/v86_offline_file.html

**Comment by Pokeplays09125** [comment]
Over the past 2 years, I've learned a lot about wasm and html, allowing me to finally get an operating system running locally about a year ago (via embedding the .wasm file as text using base64). I would attach a version I made running DSL here if it wasn't 73 megabytes.

**Comment by Pokeplays09125** [comment]
Nevermind, I found a smaller, more recent version: [saveStates.html](https://github.com/user-attachments/files/27108527/saveStates.html)
