### ISSUE TITLE
fs9p read_file strange behavior (How to detect if ready to read?)

### ISSUE THREAD

**Issue by frvnkliu** [copy/v86#1044]
Whenever I create a file in a debian container mountain fs9p, the **v86.prototype.read_file** function displays some weird behavior. 
<img width="372" alt="image" src="https://github.com/copy/v86/assets/94014427/ebb3f0d2-e38c-4906-836d-1738ed9369fe">
For the first 30 seconds after a file is created this function doesn't work, it'll return a bad promise
<img width="805" alt="image" src="https://github.com/copy/v86/assets/94014427/9f1ae738-94fe-419c-ab75-b86d178a828e">
but then after a little bit of waiting the function works fine. I was wondering if there was someway of checking if a file is ready to be read from v86.

Using Chrome's debugger I found the following:
In the fs9p.read_file:
<img width="439" alt="image" src="https://github.com/copy/v86/assets/94014427/5aaf0b8b-c259-4640-b729-9a2e4d1d21f1">
Then in fs9p.Read:
<img width="418" alt="image" src="https://github.com/copy/v86/assets/94014427/be4d6f1f-f87d-46fc-8b37-17369c85f65b">
I think this is where the issues occurs, here b and c are both 0 so the empty/null list is copied and returned.

Is there someway I can check if a file is ready for download instead of just setting a timeout to an arbitrary time?

**Comment by SuperMaxusa** [comment]
Did you try run `sync` (or `mount -o remount,sync /` before) after creating file? 
And can you also to try changing `cache=fscache` to `cache=loose` or `cache=none`?
https://github.com/copy/v86/blob/c69cbd7854d7cbda08679c389973aa87c9fb37bd/tools/docker/debian/boot-9p#L15-L16

**Comment by frvnkliu** [comment]
> Did you try run `sync` (or `mount -o remount,sync /` before) after creating file? And can you also to try changing `cache=fscache` to `cache=loose` or `cache=none`?
> 
> https://github.com/copy/v86/blob/c69cbd7854d7cbda08679c389973aa87c9fb37bd/tools/docker/debian/boot-9p#L15-L16

I have not tried to run sync yet, but I will try that soon. 

I am currently using the [v86/tools/docker/debian](https://github.com/copy/v86/tree/c69cbd7854d7cbda08679c389973aa87c9fb37bd/tools/docker/debian) to create my image, so I will also try changing `cache` to `loose` or `none`

>  `cmdline: "rw init=/bin/systemd root=host9p console=ttyS0 spectre_v2=off pti=off"`

I also write run the line above when initializing my v86 instance, but I'm notsure where I got from. Is it possible that this is causing issues?
```    js
var emulator = new V86({
    	screen_container: document.getElementById("screen_container"),
    	wasm_path: "./libs/v86.wasm",
        bios: { url: `${V86_ROOT}/bios/seabios.bin` },
        vga_bios: { url: `${V86_ROOT}/bios/vgabios.bin` },
        autostart: true,
        memory_size: 512 * 1024 * 1024,
        vga_memory_size: 8 * 1024 * 1024,
        bzimage_initrd_from_filesystem: true,
        cmdline: "rw init=/bin/systemd root=host9p console=ttyS0 spectre_v2=off pti=off",
        filesystem: {
            basefs: {
                url: `${V86_ROOT}/images/debian-base-fs.json`,
            },
            baseurl: `${V86_ROOT}/images/debian-9p-rootfs-flat/`,
        },
        autostart: true,

    });```

**Comment by SuperMaxusa** [comment]
Sorry for the late reply, that's weird that for you file is opened after 30 seconds, for example, I got maximum 5 seconds timeout on [Arch](https://copy.sh/v86/?profile=archlinux) and [Buildroot](https://copy.sh/v86/?profile=buildroot) Linux. I have some ideas about `vm.dirty_writeback_centisecs` (https://docs.kernel.org/admin-guide/sysctl/vm.html#dirty-writeback-centisecs), default value is 5000 centiseconds = 5 seconds (at least on Arch), maybe Debian has a some different value?

This can be checked with: `cat /proc/sys/vm/dirty_writeback_centisecs`

> I also write run the line above when initializing my v86 instance, but I'm notsure where I got from. Is it possible that this is causing issues?

Probably no, `spectre_v2=off pti=off` - it's disables an kernel mitigations, `root=host9p` - needed to mount root via boot-9p hook, other options in cmdline and V86 construstor look fine.

**Comment by frvnkliu** [comment]
Hi, I tried changing the cache to none and I got the following error:
<img width="505" alt="image" src="https://github.com/copy/v86/assets/94014427/f2875ab7-5d33-45de-b3be-9e447a1ecf3d">

I just checked the value of the timeout and its supposed to be 0.5 seconds.
<img width="512" alt="image" src="https://github.com/copy/v86/assets/94014427/3095c846-224c-462d-867d-08248b80655f">

**Comment by SuperMaxusa** [comment]
> I just checked the value of the timeout and its supposed to be 0.5 seconds.

I made a mistake in the previous message: **5** seconds = **500** centiseconds, and seems that your value is set to default

I wrote a small script to check the availability of a file by time:
```js
var testInterval, timer, hasError, filePath;

var test9PFS = function() { 
    window.emulator.read_file(filePath).catch((e) => {
        console.error(`File not available on ${++timer} seconds`);
        hasError = true;
    }).then(() => {
        if (!hasError) {
            console.log("File available");
            clearInterval(testInterval);
        } else {
            hasError = false;
        }
    }); 
};

var startTest = function() {
    testInterval = null, timer = 0, hasError = false, filePath = "/root/testfile";
    window.emulator.keyboard_send_text(`echo testdata > ${filePath} # AUTOMATED\n`);
    testInterval = setInterval(test9PFS, 1000);
};
```

-----------------------------

**First test**: all default settings, as you said, there is over 30 seconds timeout. And I had a some attention about [vm.dirty_expire_centiseconds](https://stackoverflow.com/questions/18353467/implementation-of-dirty-expire-centisecs), which value is 3000 centiseconds = 30 seconds, https://stackoverflow.com/questions/11884650/small-file-not-committed-to-disk-for-over-a-minute

![deb1](https://github.com/copy/v86/assets/41739128/6351130d-380b-4479-a4e4-97b4c8b6673c)

**Second test**: reduced `vm.dirty_writeback_seconds to 1 second`, I got 5 second timeout (probably it's because I didn't change `vm.dirty_writeback_centisecs`?)

![deb2](https://github.com/copy/v86/assets/41739128/9a2ba9a4-d2d5-4aaa-8504-95568c619877)

**Third test**: remount 9p as sync filesystem (or you can use a [`O_SYNC`](https://man.archlinux.org/man/open.2.en#O_SYNC) flag for `open()` syscall in your program), file opens immediately.

![deb3](https://github.com/copy/v86/assets/41739128/03fddda7-025a-4722-ba7a-7d6ae30e42b3)

-----------------------------

**Some ideas**:
 - try testing on newer versions of Debian, for example: [bookworm](https://hub.docker.com/layers/library/debian/bookworm/images/sha256-ae1d9d1f5c71e1bd305066f5bdffa3e23e4700d080a91b2d8949c2fde74e153d) (or if you build a v86 with https://github.com/copy/v86/commit/afdac896d0e948c34a88b6cb0c7829614d06756e, you can try a trixie)
 - if it's useful, you can use a `9p-write-end` event to catch the end of a file write:
 https://github.com/copy/v86/blob/c69cbd7854d7cbda08679c389973aa87c9fb37bd/src/browser/main.js#L1742-L1751

**Comment by copy** [comment]
I'll close this, as the time the guest OS decides to buffer writes is not related to v86 (but feel free to reopen if you think anything in v86 could be changed).

Also, I'd probably accept a PR that changes `9p-write-end` if there's anything missing from that event that'd be useful for you.
