### ISSUE TITLE
Double click "dos prompt" in windows 98 makes the screen look all glitchy

### ISSUE THREAD

**Issue by stuaxo** [copy/v86#110]
http://imgur.com/a/2Fmoc

**Comment by DaniellPlasmmer** [comment]
+1

http://image.prntscr.com/image/f07bb4057f8041b49869259eaa136da2.png

**Comment by copy** [comment]
It's an issue with the video driver (and the same thing happens when I load the image in QEMU): https://web.archive.org/web/20130726072031/http://www.bearwindows.boot-land.net/vbe9x.htm

> Installation note 0: Current driver unsolved problems:
> 
>    Locking and garbage problems when entering DOS WDM or console session.

The reason that we're using this driver instead of the stock driver is that we don't support all VGA features yet, see #90. This driver also has a better performance and supports bigger resolutions.

**Comment by stuaxo** [comment]
Ah, interesting :)

Bitplanes always confused me back in the day.
