### ISSUE TITLE
How to install program in Win98?

### ISSUE THREAD

**Issue by reillychase** [copy/v86#169]
Sorry if this has been asked before but I couldn't find it. How can I install a game in Win98? I want to have a game installed by default

**Comment by copy** [comment]
Games can't be easily installed in v86, due to the volatility of the disk image and #54.

What you can do instead is to download a Windows 98 image from winworldpc.com (currently down, should be back up soon) or a similar website, install it in qemu and then boot the resulting disk image in v86.

Feel free to reopen if you have more questions.

**Comment by reillychase** [comment]
wow so it is possible, that would be awesome. I will try to build my own image with qemu! Just one more question, say I want something simpler customization like including some text files in the Linux image, would the process be the same or is there an easier method? Thanks!

**Comment by copy** [comment]
Yes, for Linux the process would be the same.
