### ISSUE TITLE
Running NLTK on linux

### ISSUE THREAD

**Issue by thaiwash** [copy/v86#173]
I got the python2 hello world script working on localhost, but I cant seem to be able to modify the fs.json, since it causes a kernel panic.

Anyways, any tips on how to do this?

**Comment by copy** [comment]
What Linux are you running? Can you upload the disk image and the fs.json so I can reproduce the issue?

**Comment by thaiwash** [comment]
Err, I just copied the arch linux demo from webiste, that took a while. its
not an image, its 9p fs, and so far i got 4gb of files, so thats an issue,
unless you have an FTP address. the fs.json is 10 megabytes.
Anyways, I can send you the files if you can supply a good gateway. I'm
getting off work right now, so, I'll be deving it tomorrow prolly.

**Comment by copy** [comment]
Well, I'd suggest to create your own image first since I'm not in the hosting business and the Arch Linux image includes a lot of things that you probably don't want. Then you can also include anything you want.

Now, I don't know what causes the kernel panic, but I assume that you were missing or overrode some files that were in use.
