### ISSUE TITLE
Run the CPU in a web worker

### ISSUE THREAD

**Issue by copy** [copy/v86#20]
The [jor1k](https://github.com/s-macke/jor1k) guys do this too: Run the CPU and devices code in a web worker, saving the time for rendering. For graphical modes, this requires a significant amount of data to be transferred between the worker and the window, so it might not actually be faster (needs to be researched).

This requires some significant changes in the code, including some sort of abstraction between the code that will run in the worker and the code that will run in the window.

**Comment by warpcoil** [comment]
Hi, I'm using v86 for JSIX.  The CPU component does run well asynchronously, i.e. under a web worker.  As for screen rendering under JSIX a message passing interface acts as the intermediary.  As for you project, I only use the CPU component, it's wineapi and my code that does the render.

If I have time in the future I'll help you out, lemme get a working release first.

Now, I don't recommend "transferable objects" as they are not widely supported [IE].  As for your framebuffer, a different approach might be better, such as diffing the data and sending what has changed.

**Comment by copy** [comment]
@warpcoil JSIX sounds extremely cool, let me know if you need anything. I guess you'll at least want to hook system calls. 

I will probably use transferable objects and fall back to something slower if they're not supported (that happens automatically anyway?). The data doesn't need to be diffed, it's known which pixels are drawn. But before that, some more changes to the architecture are necessary.

**Comment by s-macke** [comment]
warpcoil, I would like to know how you solved the problem to run a web worker using 100% of the CPU but staying responsive.
I don't like my solution, which I linked above.

**Comment by copy** [comment]
@s-macke `setTimeout(tick, 0)` should do the job. I'm aware of two limitations of `setTimeout`: A 1000ms limit in inactive tabs and a 4ms general limit. The 1000ms limit doesn't apply to web workers. The 4ms limit only applies if the executing function takes less than 4ms. You can see that by benchmarking `function a() { var s = performance.now(); while(performance.now() - s < 4) {}; setTimeout(a, 0); }`

**Comment by warpcoil** [comment]
Hello, ok this is a little complex.  In jsix I have 3 threads, the browser render thread (the main thread), the processing thread, contains my version of memory, your CPU [slightly modified], PE parser, dll Handlers and the kernel32.dll.  The third worker/thread you can ignore for now [what it basically does is download a file chunk of 8Kb and renders it to memory JIT for processing].

The browser thread spawns a new thread, the processing thread.

So the app starts be it a very small app, HxD [hex editor] and notepad++ is what I am working towards, couple of weeks to a month.  You can find these files at https://github.com/warpcoil/jsixappsv1, they are just the normal files chunked up and then compressed.  The third thread [will eventually] decompresses and renders to memory in this way we are not downloading a whole filesystem.  Dlls and Executables can become very large, and still be fast because when a call occurs only an 8Kb chunk for that function is downloaded, not the entire Dll.

So you have parsed the PE header in the processing thread and a v86 object is created.  The processor starts executing until a call is made.  When a call or jump occurs, a flag stored in the memory segment is checked to see if that call should be intercepted.  In this way we can resolve function calls outside of the program to external dlls and JavaScript functions.

When a paint occurs a postMessage is posted to the primary thread for the render.

I am using a form of iterative development, and this is the third iteration.  The first version was crap, based on MIPS, linux not good.

The second version took a different approach, it was based on your v86 processor, it downloaded entire files and dlls and what not.  It works! but only to a point that processing occurs, dlls are called and so forth, before changing tact.

This is the third and final iteration, targeting a release, most of the code is ported from iter 2 [not uploaded].  The memory architecture changed even more and I am at the point of parsing the PE header getting ready to execute.

Now, I have privatised my main repo, I am fearful that when everything works [which isn't far away now] some big business is going to come along and take, take, take and no give.

You have both been given access [and eventually used as you please].  It works [will work] at the application layer as opposed to the OS Layer.

Much of the original code hasn't been uploaded to this version but should be there before too long.

Best Regards

RL

**Comment by warpcoil** [comment]
oh darn, repo is here:

https://github.com/warpcoil/jsix, jsix, v86, kernel32.dll [to port from iter 2]
Wine on Windows dlls here: https://github.com/warpcoil/jsixw2012 all chunked up and encoded [public]
Test Apps here: https://github.com/warpcoil/jsixappsv1 all chunked up and encoded [public]

**Comment by s-macke** [comment]
More than a year ago, I tried the setTimeout(tick, 0) solution. Unfortunately, it didn't check for any other messages in the message queue. So, I get a 100% usage of the worker thread, but it doesn't respond to external events. It works with a setTimeout(tick, 4); line But I would lose too much time performance.

**Comment by warpcoil** [comment]
Progress on JSIX.

We have a load screen:

![load](https://cloud.githubusercontent.com/assets/5113027/6494033/cba4b408-c2b6-11e4-85d2-9d0bc9df4f70.png)

And a window, but no menus, icons, they're all in place in the execution thread, just not in the UI thread yet.  Still quite some time off.

Apps take about 15/20 seconds on my computer (but it is more than 6 years old) and doesn't have much memory and a crap hard disk.  That said there is room for about atleast 30% optimisation and the new threading model in the next version, which downloads chunks in one web worker whilst processing them in the current one.  That separation was all planned just Chrome/Chromium needs to fix bugs in their nested web workers.  Strangle IE11 doesn't suffer from the issues Google has, shocking.

The window below is the frame of AkelPad (sans the background where you type stuff in).  Notepad++ is a little way off, I have a "SimpleWin.exe" program which works. 6 other apps are on the way too.

![window](https://cloud.githubusercontent.com/assets/5113027/6494160/a23661ce-c2b7-11e4-917a-e93b741979d2.png)

**Comment by copy** [comment]
@warpcoil Very cool!

**Comment by Creeper20428** [comment]
@warpcoil https://github.com/warpcoil/jsix is returning a 404 for me.
 

> Now, I have privatised my main repo, I am fearful that when everything works [which isn't far away now] some big business is going to come along and take, take, take and no give.

If you license it under GPL, then you'll be OK. If they use it, they'll have to give you credit. If they modify a single line, they'll have to give people the source code.

**Comment by ErnWong** [comment]
Oops, I made a typo. <sup>Sorry everyone. Please ignore that referenced commit and this message.<sup>*Thanks, bye*</sup></sup>

**Comment by BenNottelling** [comment]
@humphd If I remember correctly, more than just the CPU runs in the web worker, which may be the cause of that slowdown issue. Perhaps it's still open because of that?
Pinging @copy because he will know

**Comment by urish** [comment]
> @humphd If I remember correctly, more than just the CPU runs in the web worker, which may be the cause of that slowdown issue. Perhaps it's still open because of that?

Seems like #477 tries to address the slowdown

**Comment by copy** [comment]
The slowdown should be fixed in master. We've had (experimental) worker support for a while now, so let's close this issue.
