### ISSUE TITLE
Internet Explorer 5 crashes on any page

### ISSUE THREAD

**Issue by kenorb** [copy/v86#214]
1. Run IE 5 on https://copy.sh/v86/?profile=windows98
2. Go to: <www.example.com>

IE task crashes (it just disappears).

**Comment by tracker1** [comment]
IE5 won't work on most HTTPS sites today, the older crypto protocols are all abandoned because of security issues.

**Comment by BenNottelling** [comment]
Say that "IE task crashes" suggesting that the application crashed rather than failing to display the page @tracker1 I'm not sure how it is in IE5, but slightly newer versions will display an error on those sites rather than crashing. If that's what it does in IE5 normal then the crashing is due (likely) to an issue in v86, but if it does crash regularly then this issue can be disregarded

**Comment by BenNottelling** [comment]
This actually ISN'T an issue whatsoever. It closes and then opens a connection wizard because it's not connected to the internet. This issue should be closed

**Comment by copy** [comment]
Good point by @BenNottelling, closing.
