### ISSUE TITLE
Async Disk Loading is Very Slow

### ISSUE THREAD

**Issue by BenNottelling** [copy/v86#240]
I noticed that it took minutes to even load like 30mb of the disk which significantly seems to slow down booting of the OS. It's great because async saves some bandwidth, but it's really slow, and my VPS is more than capable of much higher speeds than that, so I'm really not sure what he issue is. Is it just not very efficient?

**Comment by copy** [comment]
That's by design, async loading means an xhr request is made for every disk access that isn't cached. It can be slightly improved by serving over a websocket connection, but I don't really want to run that kind of architecture. I'd suggest to load this image in synchronous mode (i.e., the whole file is downloaded beforehand).

**Comment by BenNottelling** [comment]
It's a 1.4GB file though. I'll look into shrinking it. Thanks for answering though!
