### ISSUE TITLE
Implement VGA Mode X

### ISSUE THREAD

**Issue by ociebieda** [copy/v86#26]
Hello.
I gived a try with this emulator.
I created many bootabla IMG disks with both, FreeDOS and MS-DOS.
FreeDOS and MS-DOS 3.3/6.x are starting up correctly, when Win 95/98 boot disks are not working.
So, I decided to check out some dos games.
On created before FreeDOS and MS-DOS bootable images I added following games: Ninja, Bruce Lee, Golden Axe, Lotus 3 - all of them are simple and work even on real 286 machine.
When I run every of these games, then screen goes 320x200 graphic mode, shows black screen and nothing more happens.
I am very surprised, because like I said, these are simple games which run on 286 computers, and you mention that this emulator is near Pentium 1 machine.
I wonder if there is something to do with emulated graphic hardware?
Thanks for any reply.

**Comment by ErnWong** [comment]
I had a look at some [vga register dumps](https://docs.google.com/spreadsheets/d/16AqaixJ2ttqWM8mCvq7Yx3JhJShTXs8jYvDspzt_eL8/edit?usp=sharing) for some video modes and programs, including these games. It turns out that Ninja and Bruce Lee uses Video Mode 4h/5h, a 4-color 320x200 resolution used when CGA were around. These two games don't work on v86 yet because our VGA implementation doesn't handle the Odd/Even Chain Modes and the Interleaved Shift Mode yet.

(I'm just throwing words around to make it sound like I know what I'm talking about :stuck_out_tongue: but in reality I'm still learning how VGA works)

Golden Axe appears to be using a flavour of the infamous Mode X.

Lotus III uses mode 13h, which has been mostly implemented correctly. If we wait long enough, you can get into the menu screen and into the game if you don't mind the slowness.

![image](https://user-images.githubusercontent.com/2609018/34538852-05ec3ff2-f133-11e7-9e20-87d996f887d7.png)

Hey @copy, would you like me to implement the odd/even/unchained modes and shift modes? It seems like a fun task, and I think I know how to do it. My intention would be to move away from using the Miscellaneous Output Register to detect the desired video modes because I don't think all programs set them consistently (e.g. [Geezer uses `0x63`](http://files.osdev.org/mirrors/geezer/osd/graphics/modes.c) while [Brackeen uses` 0xE3`](http://www.brackeen.com/vga/source/djgpp20/modes.c.html) for 320x200 unchained) and several video modes share the same Miscellaneous Output Register values. I'm thinking of adding more states to the `VGAScreen` for registers that are not handled yet, and make one big `vga_memory_write_graphical` function that handles all the graphical modes.

If you would like me to implement them, would you like me to pour everything into the current [PR](https://github.com/copy/v86/pull/178) or make a new PR?

**Comment by copy** [comment]
@ErnWong That'd be great. Your plan sounds reasonable. I'm not terribly familiar with vga, so work on this part is very much appreciated.

> If you would like me to implement them, would you like me to pour everything into the current PR or make a new PR?

I think it's fine if we add it to the existing PR.
