### ISSUE TITLE
CPU frequency is reported as 0 when measured using RDTSC

### ISSUE THREAD

**Issue by yogev1978** [copy/v86#30]
KolibriOS uses RDTSC to calculate CPU frequency. In your emulator, the CPU frequency is reported as 0 (<b>0000 MHz</b> - see attached screenshot). On real machines, the actual CPU frequency is reported. In other emulators (VMware, Oracle VirtualBox, QEMU, BOCHS) the frequency reported might be wrong (since the emulator is not running at the same speed as the host machine), but it's still not 0.

It's very much preferred not to report 0 since it affects some KolibriOS programs (Process Manager reports wrong CPU usage, Ghost Monitor thinks that CPU usage is always 100%, CPUID reports CPU speed as 0 MHz etc.)

![screenshot342](https://cloud.githubusercontent.com/assets/10349199/5578825/f650aa92-9037-11e4-8368-2dd76641fee3.png)

**Comment by yogev1978** [comment]
Thanks a lot - I have tested it on your website now, and it displays a value greater than 0. Although that value is pretty small (8 MHz), it's good enough for KolibriOS to display the CPU usage correctly.

**Comment by copy** [comment]
Yeah, it's just a constant defined [here](https://github.com/copy/v86/blob/master/src/const.js#L277) (it has to run at constant speed and the speed at which instructions are executed is not usable for that).

This was very useful because it also fixed many small problems in other operating systems, for example `clock.com` in Freedos.
