### ISSUE TITLE
Question around QEMU version

### ISSUE THREAD

**Issue by toothbrush** [copy/v86#328]
This is a rather vague question i'm afraid. I wonder what version of QEMU this is based off?  And if it's not a recent one, what would the approach be to updating to a more recent one?

I find this an amazing project, and am really keen to base a personal project off it (various Windows 98 apps in the browser) and it seems perfect for that.  However, i'm running into difficulty booting many hard disk images that work fine in Qemu 4+.

I would love to have a crack at doing the update myself, but unfortunately i can't find the documentation around the procedure for using emscripten to produce the JS code in this repository.  Any pointers? 🙌

**Comment by copy** [comment]
v86 is not based off QEMU, with the exception of some tests that we took and ran against v86.

QEMU's CPU emulation isn't easily ported to the web since it jit-compiles from an intermediate language (TCG)  to native machine code on the host (x86, arm, etc.). I think someone wrote a TCG interpreter in JavaScript some time ago, but can't find it right now and it was very slow anyway. TCG-to-wasm might be possible, but I think it's out of scope for this project.

I'm not opposed to porting other parts of QEMU to v86, for example the device emulation. We'll need to reconsider v86's license then, but I also don't mind switching to (L)GPL if necessary.

**Comment by toothbrush** [comment]
Oh, then i completely misunderstood! Is it built from scratch?  That's even more impressive then.  I thought it was similar to Bellard's jslinux.

That might explain why a lot of behaviour isn't 100% the same as QEMU, which i've been using to build images i'd like to run in my webpage.
