### ISSUE TITLE
0x020C4300 error in operating systems made with Cosmos

### ISSUE THREAD

**Issue by kilickerem066** [copy/v86#363]
So, I was creating an OS named *RadonCLI* (I will rename it to RadonOS soon 😜), and it worked normally on **VirtualBox and VMware**. I tried testing this on [copy.sh](https://copy.sh/v86/), and the output is like this:
![Screenshot](https://user-images.githubusercontent.com/64794941/88532443-493b5980-d00d-11ea-9527-52f8be16358d.png)
Please fix this. [Click here](https://github.com/CosmosOS/Cosmos) if you want to view Cosmos repository.

**Comment by pitust** [comment]
Exception 6 is invalid opcode. This is because v86 is not able to do some
fancy instruction cosmos uses that is not in the Pentium 2 instruction set.
Also, please google *before* reporting an issue. Quick Google search
revealed cpu exception 6 is invalid opcode.
Can you provide the exact code? V86's debug logs? What instruction caused
this?

**Comment by kilickerem066** [comment]
In _debug_, **this happens**:

![radon-on-copy-sh](https://user-images.githubusercontent.com/64794941/89822475-e7c0d200-db58-11ea-9fd2-88206735fa1a.png)

**Comment by pitust** [comment]
This bit is SSE enable according to wikipedia. (9th bit of cr4 does tgat)

**Comment by kilickerem066** [comment]
Can you explain **more**?

**Comment by pitust** [comment]
It enables a CPU feature called SSE. (Streaming SIMD Extensions)

**Comment by pitust** [comment]
Basically it needs something that v86 doesn't support.

**Comment by kilickerem066** [comment]
*O***h**.

**Comment by copy** [comment]
This should be fixed now.
