### ISSUE TITLE
No network after restore from stap shot

### ISSUE THREAD

**Issue by Darin755** [copy/v86#399]
There seems to be no network when restoring from snapshot. Everything seems fine except for the fact that I can not get network.

![Screenshot at 2021-02-04 09-18-50](https://user-images.githubusercontent.com/54958995/106925499-61331a80-66cd-11eb-81dd-72e74c578b70.png)
![Screenshot at 2021-02-04 09-24-37](https://user-images.githubusercontent.com/54958995/106925501-61cbb100-66cd-11eb-8c77-63f5fc3a1870.png)

**Comment by copy** [comment]
This is expected (but not documented): The mac address is not restored by default, so that restored images don't share mac addresses. As a consequence, the nic has a different mac address than the OS thinks it has. There are two options:

- Reload the ne2k driver (`rmmod ne2k-pci && modprobe ne2k-pci`). This is done in the Arch and Haiku profiles in networking.sh
- Set `preserve_mac_from_state_image: true` (currently not exposed in the UI). This is done in the Windows and ReactOS profiles.

**Comment by Darin755** [comment]
thank you
