### ISSUE TITLE
DOS text-mode menu characters rendered as "undefined"

### ISSUE THREAD

**Issue by parkertomatoes** [copy/v86#460]
Sometimes in DOS menu characters are rendered as "undefined":
<img width="1112" alt="Screen Shot 2021-04-29 at 7 05 00 AM" src="https://user-images.githubusercontent.com/6298931/116542641-df612080-a8ba-11eb-85ca-385a63890c8b.png">

I was able to reproduce this using Safari, Firefox, and Chrome on MacOS (M1), as well as Firefox and Chrome on Windows. I'm not sure what triggers it, but it wasn't always there - I remember it rendering correctly when I used v86 a year ago.

Steps to reproduce:
- Start the DOS 6.22 demo: https://copy.sh/v86/?profile=msdos
- Run the command "edit" to start the MS-DOS editor
- Press enter to close the welcome dialog
- Menu is now "undefined" repeated.

**Comment by parkertomatoes** [comment]
I took a stab at debugging this, thinking it was a simple Javascript issue due to all the "undefined"'s.

What's happening, is: 
 1. `mmap_write8` gets called with an address in the VGA text buffer range (B8000h+) and a very large value (260,000+). 
 2. That invokes [`vga_memory_write`](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/vga.js#L654), 
 3. ...which invokes [`vga_memory_write_text_mode`](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/vga.js#L885). 
 4. ...which triggers an event, ["screen-put-char"](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/browser/screen.js#L198) on the bus
 5. ...which places the value in a UInt32Array called `text_mode_data`
 6. The value [gets passed to a CP437 lookup table](https://github.com/copy/v86/blob/3791d63ffd09881782690902c6ee57f0edbd56a3/src/browser/screen.js#L478), which returns `undefined` because the table is only 256 entries and the value is very large

Masking the value at any point in that data flow is _seems like_ enough to superficially fix the issue, but why does mmap_write8 get called with a large value in the first place? I don't really know how to debug into the rust code to tell.

**Comment by copy** [comment]
There is indeed an (unwritten, and unfortunately unchecked) invariant that `mmap_write8` should only be called with values in the range 0..255. There have recently been some optimisations in the generated wasm code that violate this invariant (since in the much more common case of writing a byte to regular memory, the higher bits don't matter).

A proper fix would add the masking in the slow path of the jit memory access (`safe_write_slow_jit`), and additionally add assertions in `mmap_write{8,16}` to prevent this issue from re-appearing. Feel free to take a stab at fixing this issue (since you already debugged what went wrong). Otherwise I'll try to find time to push a fix next week.
