### ISSUE TITLE
Files put in 9p don't appear in Linux

### ISSUE THREAD

**Issue by ysangkok** [copy/v86#50]
I got 9p working alright, but the files I put there after creation of the filesystem are not visible.

For example, go here:
http://xn--kn-1ia.guru/9pdemo/basic.html

wait for it to boot and do "ls". Now choose a file and do "ls" again. The file is not visible. In jor1k this works. If I do `emulator.read_file("/filename.txt", function(err, uint8array) {if (err) console.error(err); console.log(uint8array)})`, I get the contents; so I know the uploading is working.

**Comment by copy** [comment]
The files are created in `/` (of the 9p filesystem), but apparently `/fsroot/` (of the 9p filesystem) is mounted as `/`, so files below that are never seen. A file create as follows can be seen: `emulator.create_file("/fsroot/filename.txt", new Uint8Array(32));`.

You should probably mount `/` of the 9p filesystem as `/` of the actual filesystem and recreate the filesystem json so that files are within `/` and not `/fsroot/` (maybe as issue in fs2json?).

**Comment by ysangkok** [comment]
Ah, I should have figured this out. Thanks for your research into this.
