### ISSUE TITLE
feature request: ability to configure RAM and VRAM for profiles (e.g. archlinux profile with 1gb ram)

### ISSUE THREAD

**Issue by ayunami2000** [copy/v86#510]
see title

**Comment by copy** [comment]
The controls below (including (video) memory size) already work for most profiles. Unfortunately, this is not the case for the profiles that are restored from a memory dump (Arch, Windows, ReactOS, Haiku, the BSDs and 9front) since from the OS point of view, memory size would change while it's running.

Do you actually need 1GB in the Arch profile?

**Comment by ayunami2000** [comment]
Yeah I'm running Minecraft in it and 1.8+ need more than 512mb ram. I'd set
it to 1gbram or 2gbram and either 16mb vram or 32mb vram.

**Comment by hello-smile6** [comment]
What about OS'es with hot swap support?

**Comment by pitust** [comment]
> Yeah I'm running Minecraft in it and 1.8+ need more than 512mb ram. I'd set it to 1gbram or 2gbram and either 16mb vram or 32mb vram.

minecraft is likely unplayable in v86.

**Comment by ayunami2000** [comment]
It's kinda playable on beta versions. I have a goal of making it playable.

**Comment by copy** [comment]
> What about OS'es with hot swap support?

That might work too.

I'm a bit hesitant to increase the memory size of the Arch profile. It might cause issues in mobile browsers.

**Comment by pitust** [comment]
Isn't memory hotplug a thing? i know you can hotplug cpus at least.

**Comment by copy** [comment]
Try this: https://copy.sh/v86/?profile=archlinux-boot&m=1024&vram=32
