### ISSUE TITLE
Can The Virtual Machine Detect USB Devices?

### ISSUE THREAD

**Issue by Xiji5** [copy/v86#561]
I know this might be a little advanced, and this might be too much, but is it possible that v86 can recognize my usb devices. I am using the windows 2000 demo btw. Any info would be great.

**Comment by copy** [comment]
While theoretically USB could be emulated (and WebUSB might give access to certain USB devices), due to the high effort and low gains I would say it's out of the scope for this project. Alternatively, QEMU's USB stack could be adapted, compiled to WebAssembly and linked to v86.

I think chances of either happening are fairly low, so I will close this issue (I would accept contributions though).

**Comment by Xiji5** [comment]
Well, thank you for answering, and I am glad you have thought out how this could work. Hopefully in the future this will be implemented. Still a very good online virtual machine though, if not one of the best. Welp, anyway thank you, and now I know :)

**Comment by hello-smile6** [comment]
> While theoretically USB could be emulated (and WebUSB might give access to certain USB devices), due to the high effort and low gains I would say it's out of the scope for this project. Alternatively, QEMU's USB stack could be adapted, compiled to WebAssembly and linked to v86.
> 
> I think chances of either happening are fairly low, so I will close this issue (I would accept contributions though).

Could you do it? I wanna use ADB from v86 to work on an Android phone.
