### ISSUE TITLE
Tips for implementing x86_64 support

### ISSUE THREAD

**Issue by Omay238** [copy/v86#648]
I'm going to attempt to make x86_64, so how would people suggest I do this? Any useful resources?

**Comment by copy** [comment]
Heads-up: This is probably a 3-6 month project (full-time).

The Intel software developer's manual is the main reference: https://cdrdv2.intel.com/v1/dl/getContent/671200
wiki.osdev.org is sometimes useful, e.g. https://wiki.osdev.org/Paging

I'd suggest starting with [disabling the jit](https://github.com/copy/v86/blob/adb17b7/src/rust/config.rs#L2), because that's a complex project by itself.

Breaking it down:

- Add support for switching to long mode
- Extend the instruction decoder generator (gen/generate_interpreter.js), note that some regular instructions (e.g. the brilliant single-byte `inc esp` instruction) become prefixes
- Add support for 64-bit paging (see https://github.com/copy/v86/pull/599 for an example of adding a new paging mode)
  - Probably requires adding support for NX pages, i.e. memory access from eip need an extra check
- Make register 64 bits wide (existing instructions might need to special care; for example, `mov eax, ebx` clears the upper bits of `rax`)
- Make 64-bit variants of all instructions
