### ISSUE TITLE
Linux with apt-get/composer support.

### ISSUE THREAD

**Issue by kenorb** [copy/v86#66]
Is there any possibility to run some small Linux image which can support `apt-get` or `composer`, to extend for extra packages for testing purposes? Or if this won't work.

What needs to be accomplish to make it working?

I've tried to use `wget` to download anything (or install `composer`), but it seems I couldn't make any network on any provided Linux distributions.

**Comment by copy** [comment]
It should work, but it's not the best way to do it, because networking is very slow and all data is lost when you refresh the page.

Some ways to do this are:

1. If the guest OS supports 9p (the default [Arch Linux profile](http://copy.sh/v86/?profile=archlinux) does), use 9p to transfer the files you're interested in. There's a box to transfer files in the user interface. Files appear in the root directory 
2. Include a cdrom or hard drive with the files. This is theoretically, but not currently, possible
3. If the files aren't gigantic, let me know and I'll include them. The Arch Linux profile loads files lazily, so there's no extra cost for other users

**Comment by copy** [comment]
I'm closing this, feel free to reopen if you have another question.
