### ISSUE TITLE
add usb device support via webusb

### ISSUE THREAD

**Issue by porg13231** [copy/v86#677]
see https://developer.mozilla.org/en-US/docs/Web/API/USB

**Comment by copy** [comment]
That'd be quite a bit of effort. Do you have any use-case for this?

**Comment by upintheairsheep** [comment]
I do! webUSB would be useful for connecting vintange devices to the virtual machine, or stuff like a real world usb or dvd drive.

**Comment by BelleNottelling** [comment]
> I do! webUSB would be useful for connecting vintange devices to the virtual machine, or stuff like a real world usb or dvd drive.

USB and "vintage" don't really go together

**Comment by spetterman66** [comment]
a usb floppy drive or usb stick would be great on copy.sh/v86 :)

**Comment by SuperMaxusa** [comment]
**WebUSB** blocks access to USB-HID, Mass Storage (also applies to Flash Drive and, maybe, USB-FDD/CDROM) and [some other types of devices](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/webusb/protected-interface-classes.https.any.js;l=69-89;drc=a85d452de75234046e992d4886d4e7976a4fa063), so USB-support may be partial. 

Also webusb is currently only [available](https://developer.mozilla.org/en-US/docs/Web/API/USB#browser_compatibility) in **Chromium** (and most likely, in other browsers this cannot be implemented due to [security issues](https://mozilla.github.io/standards-positions/#webusb)).

https://github.com/copy/v86/issues/561#issuecomment-978682654
