### ISSUE TITLE
stop emulator when switching tabs

### ISSUE THREAD

**Issue by ktye** [copy/v86#718]
i realized that v86 takes lot's of cpu, even when the tab is in the background.

one way to prevent this:
```js
document.onvisibilitychange=function(e) {
    if(document.visibilityState=="visible") {
           if(!emulator.is_running()) emulator.run()
    } else if( emulator.is_running()) emulator.stop()
}
```

**Comment by hello-smile6** [comment]
v86 running in the background is **helpful**...

**Comment by copy** [comment]
I don't think I will add this to libv86, since it's often useful to run v86 in the background, but embedders are obviously free to use this snippet.

That said, most OSes already properly idle (use the `hlt` instruction), and therefore don't use much CPU when idle. We should detect the idle loop of OSes that don't use `hlt` (e.g. FreeDOS) to reduce CPU usage, and I'll leave this issue open for that.

**Comment by kenorb** [comment]
Maybe adding a button to _Pause_ it, can be useful.

**Comment by Spaceboy10** [comment]
> Maybe adding a button to _Pause_ it, can be useful.

This already exists, it's beside the reset button.
![Screenshot 2022-09-16 8 41 18 AM](https://user-images.githubusercontent.com/102557131/190641361-9505e5d4-b3f7-4e15-aa60-4dc33c73774e.png)

**Comment by copy** [comment]
@ktye For FreeDOS, I suggest adding `IDLEHALT=1` to config.sys ([source](https://freedos-user.narkive.com/UGrcO8wU/does-freedos-make-cpu-sleep-when-idle)), which makes CPU usage go to almost zero.

For other OSes, I've create a new issue to improve idling: https://github.com/copy/v86/issues/877

Closing, as running v86 in the background is useful in many circumstances.
