### ISSUE TITLE
RTC bug

### ISSUE THREAD

**Issue by Pixelsuft** [copy/v86#727]
Windows NT 4.0 with MPS pc type stucks before showing the boot screen. With replaced rtc code and disabled JIT it boots (don't forget to turn on winnt_fix if you have sp1). If JIT is enabled, it will stuck at boot screen or show bsod.

**Comment by Pixelsuft** [comment]
Also, SP6 logon bug is still present...
![image](https://user-images.githubusercontent.com/68371847/188310046-a4e0291d-cd22-4f13-bf97-f2bb3d5826dd.png)

**Comment by Pixelsuft** [comment]
Using this way time sync is broken, it's very fast (may due custom rtc). But if I use Standart PC type (with this rtc) time sync works fine (almost). Also seems to be NT 4.0 uses APIC without ACPI.

**Comment by Pixelsuft** [comment]
When I've tried to install Windows NT 3.51 in QEMU, I've got this:
![image](https://user-images.githubusercontent.com/68371847/188435871-b85301d6-3997-4c91-86df-40495af41361.png)
If I disable apic, all works well.
It looks like bsod in v86 (but nt4 guest) with jit enabled (and custom rtc)

**Comment by copy** [comment]
Some things have been improved:

- rtc fix: 1a27b7231179c15d54173049597e7d18fb4acbcb
- #np on int for 3.x: 4e9ceb0ec1c8e9e19cf54fcb36114a97d0982bef
- Added two new profiles (not deployed yet): aebf5eced86a7f1060379ba6fbe7caa767ddadf5
- The netlogon issue I can't reproduce, but I'm not sure if it's properly fixed
- The crash with apic and jit is still present: The problem is that writing to apic memory can trigger an irq, and the jit does not properly bail out in that case. The apic is the only device we have that has that propery. Old pic uses io ports, and v86 always bails out after port io.

**Comment by Pixelsuft** [comment]
netlogon bug appers only with SP6
I've uploaded image [here](https://github.com/Pixelsuft/old-win-images/releases/download/v86/nt_sp6_bugged.img). (also with SP6 it loads slower)
