### ISSUE TITLE
int3 single-step debugging support

### ISSUE THREAD

**Issue by kyr0** [copy/v86#817]
Hey hey,

I just found the patch I created a year ago or so to add support for `int3` single step debugging support:

https://github.com/kyr0/v86/commit/bea3fcf2bd3076f8d8b157ed7f1845f8c02670f3

In case this is interesting for you, feel free to get inspired and integrate.

I'll update this issue as soon as I release the product that uses it :)

Best

**Comment by copy** [comment]
I had a quick look at this patch.

[INT3](https://faydoc.tripod.com/cpu/int3.htm) isn't used for single stepping (as far as I know), and is already correctly implemented in v86 (again, as far as I know).

The trap flag is used for single stepping, and is currently not implemented in v86 (#161, #278).

Since we already have issues about the trap flag, I'll close this as a duplicate.

> I'll update this issue as soon as I release the product that uses it :)

Looking forward to it :-)
