### ISSUE TITLE
I would like to download the files delivered over CDN

### ISSUE THREAD

**Issue by DarkReaper231** [copy/v86#848]
I realized that a lot of the OSes restored from snapshots are comprised of the snapshot file and the img file. I am unable to downlaod the image files because they are only delivered part by part when they're read/needed. I would like to download windows2l, windows98, windows95, redox, serenity, openbsd, reactos, 9front, haiku, arch, freebsd images from the CDN, is that possible in some sane way?

Also how do you make the snapshots? I wanted to make my own snapshot for RedstarOS from Korea (the 32bit older version one) but I am not entirely sure how you do it. Keep in mind that RedstarOS has to be installed to HDD in order to boot at all so I don't think I can go through the setup in the x86 virtualizer itself. Maybe QEMU? Is there a way?

**Comment by copy** [comment]
You can get images from https://winworldpc.com/, https://archiveos.org/, https://archive.org/, https://distrowatch.com/ etc. Almost all images on the website were installed using qemu. I don't provide direct downloads because I don't want to pay for the hosting cost.

> Also how do you make the snapshots?

There's a save state button in the UI.
