### ISSUE TITLE
Node Repl Not Working on Serial Console

### ISSUE THREAD

**Issue by copy** [copy/v86#875]
### Discussed in https://github.com/copy/v86/discussions/874

<div type='discussions-op-text'>

<sup>Originally posted by **cemalgnlts** June  6, 2023</sup>
Hi,

I am trying to start `Nodejs` in `repl` mode. I try it first in GUI (`/dev/console`) and it works successfully.
I then try to run it in the console (`/dev/ttyS0`) and it throws a strange error.

![Screenshot 2023-06-06 16 43 52](https://github.com/copy/v86/assets/45357531/b206d299-1c6a-4947-a642-7b84fb37ef3a)

The ISO file can be obtained from here:  [linux.iso](https://app.circleci.com/pipelines/github/cemalgnlts/now-linux-build/95/workflows/80c50180-95ad-487d-bc20-f0c257778d41/jobs/103/artifacts)</div>

**Comment by cemalgnlts** [comment]
I noticed that when I redirect Node's output to a file, I don't get an error:

![Screenshot 2023-06-06 19 49 53](https://github.com/copy/v86/assets/45357531/233da881-6930-461c-b7fb-a2c097966c13)

Using it this way, it takes the inputs from ttyS0 and appends the outputs to a file. I think the problem is caused by `stdin` or `stdout`.

**Comment by cemalgnlts** [comment]
I found the solution, the problem is that the ttyS0 terminal has no dimensions.

```bash
root$ stty size
stty: standard input
```

After typing the dimensions it now works fine:
```bash
root$ stty cols 80 rows 25
```

```bash
root$ stty size
25 80
```

Thanks.

**Comment by copy** [comment]
Thanks, closing.
