### ISSUE TITLE
can't build the program

### ISSUE THREAD

**Issue by Chocobonii** [copy/v86#891]
hello, whenever I try to build the program with make all, I get a lot of errors such as:
   |                               ^^^^^^
   |
  ::: src/rust/cpu/arith.rs:60:5
   |
60 |     dbg_assert!(y >= 0 && y < 0x10000);
   |     ---------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `dbg_assert` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `format` in this scope
  --> src/rust/dbg.rs:68:31
   |
68 |             log_to_js_console(format!(
   |                               ^^^^^^
   |
  ::: src/rust/cpu/arith.rs:59:5
   |
59 |     dbg_assert!(x >= 0 && x < 0x10000);
   |     ---------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `dbg_assert` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `format` in this scope
  --> src/rust/dbg.rs:68:31
   |
68 |             log_to_js_console(format!(
   |                               ^^^^^^
   |
  ::: src/rust/cpu/arith.rs:54:5
   |
54 |     dbg_assert!(y >= 0 && y < 0x10000);
   |     ---------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `dbg_assert` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find macro `format` in this scope
  --> src/rust/dbg.rs:68:31
   |
68 |             log_to_js_console(format!(
   |                               ^^^^^^
and the program is impossible to use or build, how am I supposed to build the program and run the examples?

Loading the image build/v86.wasm failed (status 404)

**Comment by copy** [comment]
Did you run `rustup target add wasm32-unknown-unknown` (or otherwise install the wasm targets)?

**Comment by Chocobonii** [comment]
ok, I have already built that and run make sucessfully but the machine still returns 404 for v86.wasm

**Comment by mrled** [comment]
I had a similar symptom on macOS, and I solved it by uninstalling rust and reinstalling from the official instructions.

I had rust installed, and had run `rustup target add wasm32-unknown-unknown`, but I continued to get a lot of errors like this. I tried `rustup target remove wasm32-unknown-unknown && rustup target add wasm32-unknown-unknown`, but the symptom didn't change. I had originally installed rust a few years ago via homebrew, and I knew it was up to date because `rustc --version` produced a timestamp from this year. Still, it didn't work until I uninstalled homebrew rust and reinstalled with instructions at https://rust-lang.org.

I'm not sure if the issue is with my homebrew install, or if it was just that it was old and upgraded and needed a clean slate.

Posting in case this helps anyone else.
