### ISSUE TITLE
Cursor misaligned

### ISSUE THREAD

**Issue by nloveladyallen** [copy/v86#93]
The host's cursor is misaligned with the guest's cursor. No matter where the host cursor is, the guest starts in the center. The guest cursor also seems to move based on the host cursor's position relative to the entire browser window, not just the emulator screen area. This occurs in all browsers (Safari 9.0.2, Chrome 49, and Firefox 45.0.1, all on OS X 10.11.2) and on all guest OSes with graphics (Windows 1.0.1, Windows 98, KolibriOS, and Solar OS), whether using copy.sh or a local server.

The issue seems to be similar to #63, but I am not using my keyboard, and the fix to #63 obviously did not solve my issue.

**Comment by copy** [comment]
The problem is in the hardware that is being emulated (a PS/2 mouse). There is no way to synchronize host mouse and guest mouse, because the emulated device only sends delta positions and we can't easily find out where the cursor in the guest operating system is.

Possible fixes are:

1. Use the "lock mouse" button. This could be made more obvious to users by enabling the same feature when clicking on the screen
2. Add support for an input device that supports absolute mouse positions on the screen (in qemu this is enabled using `-usbdevice tablet`). This should be supported by at least Windows 98, KolibriOS and Linux
3. Find the mouse position in the memory of the guest OS.

**Comment by Darker** [comment]
What about hiding the real cursor to reduce confusion? When I am playing Dungeon keeper on windows 7 I have similar problem. What I do is I temporarily set windows cursor to single dot.

**Comment by copy** [comment]
@Darker That's exactly what happens when you use "lock mouse"
