### ISSUE TITLE
Unimplemented: PAE

### ISSUE THREAD

**Issue by Darker** [copy/v86#97]
This is a message I get when booting Debian 8. I know that's a new system but I thought it would be really cool to run actual modern working OS in the emulator. What would be needed to fix that error? I'm a javascript programmer and I'd really like to help!

**Comment by warpcoil** [comment]
PAE is the Physical Address Extensions of the Paging System on x86 platforms.  You can find out more here:

http://wiki.osdev.org/PAE

It shouldn't be too difficult to extend the existing paging mechanism in v86 . . .  I wouldn't be surprised if that was the only issue when booting Debian 8 though.

**Comment by Darker** [comment]
Well, I don't know anything about operating systems and low level operation. I guess I could follow some documentation and verbatim implement what the documentation says.

**Comment by copy** [comment]
PAE is described in [this manual](https://www-ssl.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-system-programming-manual-325384.pdf).

Normal 32-bit paging is implemented [here](https://www-ssl.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf). PAE paging follows the same structure, but there is an extra indirection, the tables have different sizes and each entry is 64 bit.

Note that PAE is actually quite useless since JavaScript can't address that much memory anyway. Actually, it's bad for performance (you can see that PAE translation is more complex that normal 32-bit translation). It would be a better idea to install Debian with a non-pae kernel. I'll give it a try.

>  I wouldn't be surprised if that was the only issue when booting Debian 8 though.

The only thing that comes to mind is MMX/SSE.

**Comment by copy** [comment]
Debian 8.4 boots perfectly fine after installing `linux-image-586`. Maybe I'll release this on the front page.

I'll leave this issue open for PAE anyway.

**Comment by warpcoil** [comment]
Yeah, I done some experiments too . . .  Gentoo latest works as well

**Comment by ayunami2000** [comment]
bump. even if it seems useless, many OSes (namely newer versions of windows) require this and refuse to boot without it.

**Comment by iAmInActions** [comment]
Any updates regarding this?

**Comment by copy** [comment]
v86 is small project with a small number of non-fulltime contributors. As far as I know, nobody is currently working on this. If you really want it, feel free to contribute it yourself.

**Comment by iAmInActions** [comment]
im not good at wasm so i probably cant help

**Comment by BenNottelling** [comment]
PAE was recently added, any reason to keep this open?

**Comment by copy** [comment]
Nope, fixed in #599.

**Comment by ayunami2000** [comment]
That's kinda sick ngl, can't wait to test this! Thank you so much for all the work put into this project, it really is awesome work that you are doing here!!

**Comment by iAmInActions** [comment]
Time to install Ubuntu 20.04 and Windows 7 or 8.1
