### ISSUE TITLE
Update Android-x86 Boot Time

### ISSUE THREAD

**Issue by fullpwn** [copy/v86#991]
On Macbook Air M2, Android took 48 seconds to boot from live cd menu to home. 

On the list it says it will take 10 minutes to boot.

**Comment by spetterman66** [comment]
It depends on the host system's speed. With your MacBook Air M2, it'll be quite fast, due to it being based on the new Apple Silicon architecture.
________________________________
From: fullpwn ***@***.***>
Sent: Sunday, February 11, 2024 7:50 AM
To: copy/v86 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [copy/v86] Update Android-x86 Boot Time (Issue #991)


On Macbook Air M2, Android took 48 seconds to boot from live cd menu to home.

On the list it says it will take 10 minutes to boot.
